const copy={
  en:{brand:'Memory Manager',eyebrow:'Windows · Local-first · Safety-first',heroA:'Make memory control',heroB:'quiet, clear, and useful.',heroText:'Monitor memory pressure, protect multiple games, manage safely idle background apps, and keep every action behind explicit safety checks. No third-party tracking, and no fake “one-click RAM purge” tricks.',github:'View on GitHub',local:'Runs locally',privacy:'No third-party tracking',games:'Multi-game protection',available:'Available RAM',normal:'Normal',protected:'Protected',idle:'Idle low-priority',history:'Memory history',safetyLine:'Foreground, system, game and anti-cheat processes stay protected',uiLine:'Smooth UI with native Windows control underneath',privacyLine:'Local-first settings and diagnostics without trackers',featureEyebrow:'Not another “RAM cleaner”',featureTitle:'Know why, before anything changes.',featureText:'From memory history and multi-game protection to reversible memory-priority changes, every feature is designed to be understandable and verifiable.',f1t:'Pressure-aware control',f1p:'Combines available RAM, Commit, Windows signals and safety roles before acting.',f2t:'Multi-game protection',f2p:'Protect multiple game executables from automatic trim and low-memory-priority cooling.',f3t:'Live process view',f3p:'Grouping, icons, Working Set, Private Memory and RAM deltas in one place.',f4t:'Reversible policy',f4p:'Tracks memory-priority changes made by the manager and restores them when needed.',f5t:'Floating status orb',f5p:'Keep available RAM, Commit and pressure status visible without opening the main window.',f6t:'Three languages + themes',f6p:'English, Traditional Chinese and Simplified Chinese with dark, light and custom accents.',ctaEyebrow:'Memory Manager',ctaTitle:'Want to see how it works?',ctaText:'Source, versions and updates live on GitHub. Usage demos and walkthroughs are published on YouTube.'},
  'zh-TW':{brand:'記憶體管理器',eyebrow:'Windows · 本機優先 · 安全優先',heroA:'把記憶體控制',heroB:'做得安靜又清楚。',heroText:'即時監控記憶體壓力、保護多款遊戲、管理閒置背景程式，並保留每一步安全檢查。沒有第三方追蹤，也不靠誇張的「一鍵清空 RAM」。',github:'查看 GitHub',local:'本機運作',privacy:'無第三方追蹤',games:'多遊戲保護',available:'可用記憶體',normal:'正常',protected:'受保護',idle:'閒置低優先',history:'記憶體歷史',safetyLine:'前景、系統、遊戲與反作弊程式持續受保護',uiLine:'流暢 UI，原生 Windows 控制能力',privacyLine:'設定與診斷以本機為主，不植入追蹤器',featureEyebrow:'不是「清 RAM」小工具',featureTitle:'每個動作，都先知道為什麼。',featureText:'從記憶體歷史、多遊戲保護到可回復的記憶體優先順序，功能以可理解、可驗證為優先。',f1t:'智慧壓力控制',f1p:'依可用 RAM、Commit、Windows 訊號與安全角色決定是否介入。',f2t:'多遊戲保護',f2p:'同時保護多個遊戲執行檔，避免自動 Trim 或降低記憶體優先順序。',f3t:'即時程式視圖',f3p:'群組、圖示、Working Set、Private Memory 與 RAM 變化量一眼看懂。',f4t:'可回復策略',f4p:'記錄由管理器調整的記憶體優先順序，必要時可一鍵還原。',f5t:'懸浮狀態球',f5p:'在桌面上快速掌握可用 RAM、Commit 與目前壓力狀態。',f6t:'三語與自訂主題',f6p:'English、繁體中文、简体中文，搭配深淺色與自訂 Accent。',ctaEyebrow:'記憶體管理器',ctaTitle:'想看看它怎麼做？',ctaText:'原始碼、版本與後續更新都會整理在 GitHub；使用示範則放在 YouTube。'},
  'zh-CN':{brand:'内存管理器',eyebrow:'Windows · 本机优先 · 安全优先',heroA:'让内存控制',heroB:'安静、清楚、真正有用。',heroText:'实时监控内存压力、保护多款游戏、管理安全闲置的后台程序，并为每一步保留安全检查。没有第三方跟踪，也不靠夸张的“一键清空 RAM”。',github:'查看 GitHub',local:'本机运行',privacy:'无第三方跟踪',games:'多游戏保护',available:'可用内存',normal:'正常',protected:'受保护',idle:'闲置低优先',history:'内存历史',safetyLine:'前台、系统、游戏与反作弊进程持续受保护',uiLine:'流畅 UI，底层保留原生 Windows 控制能力',privacyLine:'设置与诊断以本机为主，不加入跟踪器',featureEyebrow:'不是“清 RAM”小工具',featureTitle:'每个动作，都先知道为什么。',featureText:'从内存历史、多游戏保护到可恢复的内存优先级，每项功能都优先做到可理解、可验证。',f1t:'智能压力控制',f1p:'根据可用 RAM、Commit、Windows 信号与安全角色决定是否介入。',f2t:'多游戏保护',f2p:'同时保护多个游戏可执行文件，避免自动 Trim 或降低内存优先级。',f3t:'实时进程视图',f3p:'分组、图标、Working Set、Private Memory 与 RAM 变化量一眼看懂。',f4t:'可恢复策略',f4p:'记录管理器调整过的内存优先级，需要时可以一键恢复。',f5t:'悬浮状态球',f5p:'无需打开主窗口，也能快速掌握可用 RAM、Commit 与压力状态。',f6t:'三语与自定义主题',f6p:'English、繁體中文、简体中文，并支持深浅色和自定义 Accent。',ctaEyebrow:'内存管理器',ctaTitle:'想看看它怎么做？',ctaText:'源码、版本与后续更新都会整理在 GitHub；使用演示会发布到 YouTube。'}
};
let lang='zh-TW';
const applyLang=next=>{lang=copy[next]?next:'zh-TW';document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(copy[lang][k]!=null)el.textContent=copy[lang][k]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.title=`${copy[lang].brand} · Memory Manager`};
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>applyLang(b.dataset.lang)));
document.querySelector('#themeToggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light'});
if(matchMedia('(prefers-color-scheme: light)').matches)document.documentElement.dataset.theme='light';
applyLang('zh-TW');
