const I18N={
  'zh-TW':{brand:'記憶體管理器',navFeatures:'功能',navInstall:'安裝',navLogs:'Log',navSafety:'安全',eyebrow:'Windows 11 · 本機優先 · 安全優先',heroA:'把記憶體控制',heroB:'做得安靜又清楚。',heroText:'不是「一鍵清 RAM」的魔法按鈕。它先告訴你 RAM、Commit、程式增長與風險，再用白話說明現在要不要處理。',download:'下載最新版',youtube:'YouTube 頻道',proof1:'1 ms 起資料取樣',proof2:'Log 白話化',proof3:'真正安裝 / 修復 / 移除',available:'可用 RAM',normal:'正常',sampling:'取樣',pressure:'記憶體壓力',newUpdate:'新功能與改進',notifText:'通知中心、簡單 Log、真正安裝器',logOk:'不用看天書',logExample:'02:31 · 更新檢查完成，沒有問題',q1:'資料可以高頻取樣；畫面另行節流，不讓監控工具自己吃掉效能。',q2:'把「快用完了嗎？」轉成百分比、Headroom 與趨勢 ETA。',q3:'先告訴你哪個一般程式最值得正常關閉，不直接亂殺系統程序。',featureEyebrow:'beta.28 · 20+ 個實際功能',featureTitle:'功能很多，但不用先變成工程師。',featureText:'專業資料留在底層；畫面先回答三件事：現在正常嗎？哪裡在變？我需要做什麼？',logTitle:'Log 不該像考試題。',logText:'原始紀錄仍保留，但 App 內先把常見事件翻成簡單句子。需要深入檢查時，再按「開啟 Log 資料夾」看完整檔案。',notifyTitle:'更新會提醒，但不一直吵你。',notifyText:'App 會定期檢查 GitHub Releases；發現新版本時放進通知頁並顯示 Windows 本機通知。這是背景 polling，不會假裝成伺服器 true push。',installTitle:'「安裝」就真的安裝。',installText:'Setup 不是假的進度條。它會把程式放到使用者程式目錄、建立開始功能表與桌面捷徑，並加入 Windows 解除安裝清單。',safetyTitle:'先避免把「優化」做成新的問題。',finalTitle:'想控制記憶體，不必先學會看天書。',finalText:'先下載、先看懂，再決定要不要動。原始碼、Release 與版本紀錄全部放在 GitHub。'},
  'zh-CN':{brand:'内存管理器',navFeatures:'功能',navInstall:'安装',navLogs:'日志',navSafety:'安全',eyebrow:'Windows 11 · 本地优先 · 安全优先',heroA:'把内存控制',heroB:'做得安静又清楚。',heroText:'不是“一键清 RAM”的魔法按钮。它先告诉你 RAM、Commit、程序增长与风险，再用白话说明现在要不要处理。',download:'下载最新版',youtube:'YouTube 频道',proof1:'1 ms 起数据采样',proof2:'日志白话化',proof3:'真正安装 / 修复 / 卸载',available:'可用 RAM',normal:'正常',sampling:'采样',pressure:'内存压力',newUpdate:'新功能与改进',notifText:'通知中心、简单日志、真正安装器',logOk:'不用看天书',logExample:'02:31 · 更新检查完成，没有问题',featureEyebrow:'beta.28 · 20+ 个实际功能',featureTitle:'功能很多，但不用先变成工程师。',featureText:'专业数据留在底层；界面先回答三件事：现在正常吗？哪里在变？我需要做什么？',logTitle:'日志不该像考试题。',notifyTitle:'更新会提醒，但不会一直打扰你。',installTitle:'“安装”就真的安装。',safetyTitle:'先避免把“优化”做成新的问题。',finalTitle:'想控制内存，不必先学会看天书。'},
  en:{brand:'Memory Manager',navFeatures:'Features',navInstall:'Install',navLogs:'Logs',navSafety:'Safety',eyebrow:'Windows 11 · Local-first · Safety-first',heroA:'Memory control,',heroB:'quiet and understandable.',heroText:'Not a magic “clear RAM” button. It shows RAM, commit pressure, growth and risk first, then explains whether you actually need to act.',download:'Download latest',youtube:'YouTube channel',proof1:'Telemetry from 1 ms',proof2:'Plain-language logs',proof3:'Real install / repair / remove',available:'Available RAM',normal:'Normal',sampling:'Sampling',pressure:'Memory Pressure',newUpdate:'Features & improvements',notifText:'Notifications, simple logs, real installer',logOk:'Readable logs',logExample:'02:31 · Update check finished, no action needed',q1:'High-frequency telemetry is separated from UI refresh so the monitor does not become the load.',q2:'Commit percentage, headroom and trend ETA answer “are we running out?”',q3:'Suggest normal closing of large user apps before touching protected system processes.',featureEyebrow:'beta.28 · 20+ practical features',featureTitle:'Powerful underneath. Understandable on top.',featureText:'The UI answers three questions first: is it healthy, what is changing, and what should I do?',logTitle:'Logs should not read like an exam.',logText:'Raw records remain available, while common events are translated into plain language in the app.',notifyTitle:'Updates can notify you without nagging.',notifyText:'The app periodically checks GitHub Releases and posts an in-app/local Windows notification when a version changes. This is polling, not fake “true push”.',installTitle:'Install means a real install.',installText:'Setup copies the app, creates shortcuts and registers an uninstall entry in Windows.',safetyTitle:'Optimization should not become a new problem.',finalTitle:'Control memory without learning a wall of jargon first.',finalText:'Download it, understand the state, then decide whether anything needs changing.'}
};
let lang=localStorage.getItem('mm-lang')||'zh-TW';
function setLang(next){lang=I18N[next]?next:'zh-TW';localStorage.setItem('mm-lang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=I18N[lang][el.dataset.i18n];if(v)el.textContent=v});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(lang);
const root=document.documentElement;const stored=localStorage.getItem('mm-theme');if(stored)root.dataset.theme=stored;document.querySelector('#themeToggle').addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('mm-theme',root.dataset.theme)});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('on')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
const states=[{ram:'8.6 GB',commit:'64%',head:'12.4 GB',label:'Stable'},{ram:'7.9 GB',commit:'69%',head:'10.8 GB',label:'Game detected'},{ram:'9.4 GB',commit:'61%',head:'13.5 GB',label:'Background optimized'},{ram:'8.8 GB',commit:'63%',head:'12.9 GB',label:'Stable'}];let si=0;setInterval(()=>{si=(si+1)%states.length;const s=states[si];document.querySelector('#ramValue').textContent=s.ram;document.querySelector('#commitValue').textContent=s.commit;document.querySelector('#headroomValue').textContent=s.head;document.querySelector('#chartLabel').textContent=s.label},2400);
