const TK='auth:tokens',CS=10485760;
export default{async fetch(r,e){try{return await h(r,e)}catch(x){return J({ok:false,error:String(x?.message||x)},500)}}};
async function h(r,e){let u=new URL(r.url),p=u.pathname;
 if(p==='/'&&r.method==='GET')return J({service:'onedrive-cn-bridge',health:'/health',setup:'Set ACCESS_KEY, MS_CLIENT_ID and MS_CLIENT_SECRET secrets, register /auth/callback as redirect URI, then POST /api/auth/url with Bearer ACCESS_KEY.'});
 if(p==='/health')return J({ok:true,microsoftConfigured:!!(e.MS_CLIENT_ID&&e.MS_CLIENT_SECRET),accessKeyConfigured:!!e.ACCESS_KEY,basePath:e.BASE_PATH||'CloudflareBridge',chunkSize:CS});
 if(p==='/auth/callback')return cb(r,e);
 if(p.startsWith('/d/')&&r.method==='GET')return dl(r,e,p.slice(3));
 if(!auth(r,e))return J({ok:false,error:'Unauthorized'},401);
 if(p==='/api/status')return status(e);
 if(p==='/api/auth/url'&&r.method==='POST')return au(r,e);
 if(p==='/api/files'&&r.method==='GET')return files(e);
 if(p==='/api/upload/start'&&r.method==='POST')return us(r,e);
 let m=p.match(/^\/api\/upload\/([^/]+)$/);if(m&&r.method==='PUT')return uc(r,e,m[1]);
 m=p.match(/^\/api\/upload\/([^/]+)\/status$/);if(m&&r.method==='GET')return ust(e,m[1]);
 m=p.match(/^\/api\/download-ticket\/([^/]+)$/);if(m&&r.method==='POST')return dt(e,decodeURIComponent(m[1]));
 return J({ok:false,error:'Not found'},404)}
function auth(r,e){return !!e.ACCESS_KEY&&(r.headers.get('authorization')||'')===`Bearer ${e.ACCESS_KEY}`}
function cfg(e){if(!e.MS_CLIENT_ID||!e.MS_CLIENT_SECRET)throw Error('MS_CLIENT_ID/MS_CLIENT_SECRET not configured')}
async function status(e){let t=await e.STATE.get(TK,'json');return J({ok:true,microsoftConfigured:!!(e.MS_CLIENT_ID&&e.MS_CLIENT_SECRET),accessKeyConfigured:!!e.ACCESS_KEY,connected:!!(t?.refresh_token||t?.access_token),basePath:e.BASE_PATH||'CloudflareBridge',chunkSize:CS})}
async function au(r,e){cfg(e);let o=new URL(r.url).origin,s=crypto.randomUUID();await e.STATE.put('oauth:'+s,'1',{expirationTtl:600});let u=new URL(`https://login.microsoftonline.com/${encodeURIComponent(e.MS_TENANT||'common')}/oauth2/v2.0/authorize`);for(let[k,v]of Object.entries({client_id:e.MS_CLIENT_ID,response_type:'code',redirect_uri:o+'/auth/callback',response_mode:'query',scope:'offline_access Files.ReadWrite User.Read',state:s}))u.searchParams.set(k,v);return J({ok:true,url:u.toString(),redirectUri:o+'/auth/callback'})}
async function cb(r,e){cfg(e);let u=new URL(r.url),c=u.searchParams.get('code'),s=u.searchParams.get('state');if(!c||!s||!await e.STATE.get('oauth:'+s))return T('Invalid OAuth callback',400);await e.STATE.delete('oauth:'+s);let q=new URLSearchParams({client_id:e.MS_CLIENT_ID,client_secret:e.MS_CLIENT_SECRET,grant_type:'authorization_code',code:c,redirect_uri:u.origin+'/auth/callback',scope:'offline_access Files.ReadWrite User.Read'}),z=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(e.MS_TENANT||'common')}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:q}),t=await z.json();if(!z.ok)return T(t.error_description||t.error||'token error',502);t.expires_at=Date.now()+(Number(t.expires_in||3600)-60)*1000;await e.STATE.put(TK,JSON.stringify(t));await folder(e,t.access_token);return Response.redirect(u.origin+'/?connected=1',302)}
async function at(e){cfg(e);let t=await e.STATE.get(TK,'json');if(!t)throw Error('OneDrive not connected');if(t.access_token&&Date.now()<t.expires_at)return t.access_token;if(!t.refresh_token)throw Error('Missing refresh token');let q=new URLSearchParams({client_id:e.MS_CLIENT_ID,client_secret:e.MS_CLIENT_SECRET,grant_type:'refresh_token',refresh_token:t.refresh_token,scope:'offline_access Files.ReadWrite User.Read'}),z=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(e.MS_TENANT||'common')}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:q}),n=await z.json();if(!z.ok)throw Error(n.error_description||n.error||'refresh error');t={...t,...n,expires_at:Date.now()+(Number(n.expires_in||3600)-60)*1000};await e.STATE.put(TK,JSON.stringify(t));return t.access_token}
async function G(e,p,i={}){let H=new Headers(i.headers||{});H.set('authorization','Bearer '+await at(e));if(i.body&&!H.has('content-type'))H.set('content-type','application/json');return fetch('https://graph.microsoft.com/v1.0'+p,{...i,headers:H})}
async function folder(e,t){let b=e.BASE_PATH||'CloudflareBridge',H={authorization:'Bearer '+(t||await at(e))},z=await fetch('https://graph.microsoft.com/v1.0/me/drive/root:/'+encodeURIComponent(b),{headers:H});if(z.ok)return;if(z.status!==404)throw Error('Folder check failed '+z.status);z=await fetch('https://graph.microsoft.com/v1.0/me/drive/root/children',{method:'POST',headers:{...H,'content-type':'application/json'},body:JSON.stringify({name:b,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!z.ok&&z.status!==409)throw Error('Folder create failed '+z.status)}
async function files(e){await folder(e);let b=e.BASE_PATH||'CloudflareBridge',z=await G(e,`/me/drive/root:/${encodeURIComponent(b)}:/children?$select=id,name,size,file,folder,lastModifiedDateTime&$top=200`),d=await z.json();return J(z.ok?{ok:true,files:(d.value||[]).map(x=>({id:x.id,name:x.name,size:x.size,file:!!x.file,folder:!!x.folder,lastModifiedDateTime:x.lastModifiedDateTime}))}:{ok:false,error:d?.error?.message||'Graph error'},z.status)}
function fn(n){return String(n||'').trim().replace(/[\\/\0\r\n]/g,'_').slice(0,240)}
async function us(r,e){let a=await r.json(),n=fn(a.name),s=Number(a.size);if(!n||!Number.isSafeInteger(s)||s<=0)return J({ok:false,error:'Invalid name/size'},400);await folder(e);let b=e.BASE_PATH||'CloudflareBridge',z=await G(e,`/me/drive/root:/${encodeURIComponent(b)}/${encodeURIComponent(n)}:/createUploadSession`,{method:'POST',body:JSON.stringify({item:{'@microsoft.graph.conflictBehavior':'rename',name:n}})}),d=await z.json();if(!z.ok||!d.uploadUrl)return J({ok:false,error:d?.error?.message||'createUploadSession failed'},z.status);let id=crypto.randomUUID(),exp=Date.parse(d.expirationDateTime||'')||Date.now()+3600000,ttl=Math.max(60,Math.min(86400,Math.floor((exp-Date.now())/1000)));await e.STATE.put('up:'+id,JSON.stringify({url:d.uploadUrl,name:n,size:s}),{expirationTtl:ttl});return J({ok:true,uploadId:id,chunkSize:CS,expirationDateTime:d.expirationDateTime})}
async function uc(r,e,id){let s=await e.STATE.get('up:'+id,'json');if(!s)return J({ok:false,error:'Upload session expired'},404);let cr=r.headers.get('content-range'),l=Number(r.headers.get('content-length'));if(!cr||!Number.isSafeInteger(l)||l<=0||l>=62914560||!r.body)return J({ok:false,error:'Content-Range/Content-Length required; chunk <60MiB'},400);let f=new FixedLengthStream(l),pump=r.body.pipeTo(f.writable),z=await fetch(s.url,{method:'PUT',headers:{'content-range':cr,'content-type':'application/octet-stream'},body:f.readable});await pump;let x=await z.text(),d;try{d=x?JSON.parse(x):null}catch{d=x}if(z.status===200||z.status===201)await e.STATE.delete('up:'+id);return J({ok:z.ok,status:z.status,upstream:d},z.status)}
async function ust(e,id){let s=await e.STATE.get('up:'+id,'json');if(!s)return J({ok:false,error:'Upload session expired'},404);let z=await fetch(s.url),x=await z.text(),d;try{d=x?JSON.parse(x):null}catch{d=x}return J({ok:z.ok,status:z.status,session:d},z.status)}
async function dt(e,id){let t=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');await e.STATE.put('dl:'+t,JSON.stringify({id}),{expirationTtl:3600});return J({ok:true,url:'/d/'+t,expiresIn:3600})}
async function dl(r,e,t){let q=await e.STATE.get('dl:'+t,'json');if(!q)return T('Download ticket expired',404);let z=await G(e,`/me/drive/items/${encodeURIComponent(q.id)}?$select=id,name,size,@microsoft.graph.downloadUrl`),d=await z.json();if(!z.ok)return T(d?.error?.message||'Graph error',z.status);let H=new Headers(),ra=r.headers.get('range'),ir=r.headers.get('if-range');if(ra)H.set('range',ra);if(ir)H.set('if-range',ir);let x=await fetch(d['@microsoft.graph.downloadUrl'],{headers:H,redirect:'follow'}),O=new Headers(x.headers);O.set('cache-control','private, no-store');O.set('content-disposition',`attachment; filename*=UTF-8''${encodeURIComponent(d.name||'download.bin')}`);return new Response(x.body,{status:x.status,statusText:x.statusText,headers:O})}
function J(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}function T(x,s=200){return new Response(String(x),{status:s,headers:{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'}})}
